# Generated by Django 3.0.6 on 2020-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Image Name'),
        ),
    ]
