# Generated by Django 3.0.6 on 2020-06-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200620_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ocr',
            new_name='ocrStatusChoice',
        ),
    ]
