# Generated by Django 3.0.6 on 2020-06-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebase',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
