# Generated by Django 3.0.6 on 2020-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0005_auto_20200620_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='firmness',
        ),
        migrations.AddField(
            model_name='image',
            name='ocr',
            field=models.CharField(choices=[('awaitingocr', 'AwaitingOCR'), ('soft', 'Soft'), ('semi-soft', 'Semi-Soft'), ('semi-hard', 'Semi-Hard'), ('hard', 'Hard')], default='awaitingocr', max_length=20, verbose_name='OCR Status'),
        ),
    ]
