# Generated by Django 3.0.6 on 2020-06-20 22:34

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0007_auto_20200620_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', primary_key=True, serialize=False, unique=True, verbose_name='File Slug')),
                ('unscannedFile', models.FileField(default='unscannedfiles/default.jpg', upload_to='unscannedfiles/')),
                ('ocrStatusChoice', models.CharField(choices=[('awaitingocr', 'AwaitingOCR'), ('queuedforocr', 'QueuedForOCR'), ('completedocr', 'CompletedOCR')], default='awaitingocr', max_length=20, verbose_name='OCR Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
