# Generated by Django 3.0.6 on 2020-06-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0008_auto_20200620_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fileupload',
            new_name='File_upload',
        ),
    ]
