# Generated by Django 3.0.6 on 2020-06-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0009_auto_20200620_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='unscannedFile',
            new_name='uploadedFile',
        ),
    ]
