# Generated by Django 3.0.6 on 2020-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0010_auto_20200623_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='uploadedBy',
            field=models.CharField(default='undefined', max_length=255, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='name',
            field=models.CharField(default='undefined', max_length=255, verbose_name='File Name'),
        ),
    ]
