# Generated by Django 3.0.6 on 2020-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0011_auto_20200704_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uploadedFile',
            field=models.FileField(default='ocr_osler/file_uploads/unscannedfiles/default.jpg', upload_to='ocr_osler/file_uploads/unscannedfiles/'),
        ),
    ]
